development:
  adapter: postgresql
  encoding: utf8
  database: debrief_development
  pool: 20
  username: deploy
  password: dabakh
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: debrief_test
  pool: 20
  username: deploy
  password: dabakh
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: debrief_production
  pool: 20
  username: deploy
  password: dabakh
  host: localhost